# Deploy single helm chart found in this repo as a multiple healm releases with different values at 'k8s-operator' cluster to namespace 'default'
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: multi-app-single-cluster
  namespace: argocd
spec:
  generators:
    # https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Git/
    - git:
        repoURL: git@github.com:m-wrzesien/infoshare-2023.git
        revision: master
        directories:
          - path: app/chart/apps/*
  template:
    metadata:
      name: "multi-app-single-cluster-{{path.basename}}-k8s-operator" # 'path.basename' - name of one of the folder that match wildcard (e.g. app-a)
    spec:
      destination:
        name: k8s-operator
        namespace: default
      project: default
      source:
        path: app/chart
        repoURL: git@github.com:m-wrzesien/infoshare-2023.git
        targetRevision: master
        helm:
          releaseName: multi-app-single-cluster-{{path.basename}}
          valueFiles:
            - values.yaml
            - 'apps/{{path.basename}}/values.singleCluster.yaml'  # paths is relative to the 'path' field
