# Deploy single helm chart found in this repo as a multiple helm releases with different values to each registed cluster to namespace 'default'
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: multi-app-multi-cluster
  namespace: argocd
spec:
  generators:
    # https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Matrix/
    - matrix:
        generators:
          - git:
              repoURL: git@github.com:m-wrzesien/infoshare-2023.git
              revision: master
              directories:
                - path: app/chart/apps/*
          - clusters: {} # Automatically use all clusters defined within Argo CD
  template:
    metadata:
      name: "multi-app-multi-cluster-{{path.basename}}-{{name}}"
    spec:
      destination:
        name: "{{name}}"
        namespace: default
      project: default
      source:
        path: app/chart
        repoURL: git@github.com:m-wrzesien/infoshare-2023.git
        targetRevision: master
        helm:
          releaseName: multi-app-multi-cluster-{{path.basename}}
          valueFiles:
            - values.yaml
            - "apps/{{path.basename}}/values.multiCluster.yaml"
