# Deploy helm chart found in this repo at 'k8s-operator' cluster to namespace 'default'
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: single-app-k8s-operator
  namespace: argocd
spec:
  destination:
    name: k8s-operator
    namespace: default
  project: default
  source:
    path: app/chart
    repoURL: git@github.com:m-wrzesien/infoshare-2023.git
    targetRevision: master
    helm:
      releaseName: single-app
