# Deploy helm chart found in this repo on every cluster registed at Argo CD on namespace 'default'
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: single-app-multi-cluster
  namespace: argocd
spec:
  generators:
    # https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Cluster/
    - clusters: {} # Automatically use all clusters defined within Argo CD
  template:
    metadata:
      name: "single-app-multi-cluster-{{name}}" # 'name' field of the Secret, which is just a cluster name
    spec:
      destination:
        name: "{{name}}" # 'name' field of the Secret, which is just a cluster name
        namespace: default
      project: default
      source:
        path: app/chart
        repoURL: git@github.com:m-wrzesien/infoshare-2023.git
        targetRevision: master
        helm:
          releaseName: single-app-multi-cluster
          valueFiles:
            - values.yaml
            - values.multiCluster.yaml
